### ISSUE TITLE
Composition field name suggestions

### ISSUE THREAD

**Issue by muvaf** [negz/example-cnp#7]
A `Composition` looks like:
```yaml
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: Composition
metadata:
  name: clusters.cnp.example.org
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  reclaimPolicy: Delete
  compositeResource:
    apiVersion: cnp.example.org/v1alpha1
    kind: AllocatedCluster
  composedResources:
  - base:
      apiVersion: clusters.cnp.example.org/v1alpha1
      kind: EKS
    patches:
    - fromFieldPath: metadata.annotations[crossplane.io/external-name]
      toFieldPath: metadata.annotations[crossplane.io/external-name]
    - fromFieldPath: metadata.uid
      toFieldPath: spec.writeConnectionSecretToRef.name
      transforms:
      - type: string
        string:
          fmt: "%s-eks"
...
```

* `compositeResource`: I think from the first look `compositeResource` could feel like an actual resource but it's actually a type reference, i.e. it has only `apiVersion` and `kind`. So, `compositeKind`, `compositeType`, `targetKind` or `targetType` or even just `type` or `definition`/`targetDefinition` could give more clues about what it is immediately.

* `composedResources`: it could be `resourceTemplates` or just `resources`/`templates` since being editing a `Composition` kind already implies that these are the composed resources.

* `fromFieldPath`: Since we'll be doing bidirectional patches, it could make sense to imply the direction in the field names. For example, `fromComposite`/`toResource` and `fromResource`/`toComposite`. I believe `*FieldPath` is not worth to include since it's already implied that it's a field path. In cases it's not, it's very clear like `value`.
  * We may end up with a separate top field instead of reusing `patches` but I think this would still apply.
